#!/bin/bash

LOCK="󰌾  Lock"
SUSPEND="󰤄  Suspend"
LOGOUT="󰍃  Logout"
REBOOT="󰑓  Reboot"
SHUTDOWN="󰐥  Shutdown"

# Navigation (Ctrl+hjkl, hover-select, mouse) comes from the global config.rasi.
POWER_MENU_ARGS=(
    -p ""
    -theme "$HOME/.config/rofi/themes/power-menu.rasi"
)

chosen=$(printf "%s\n" "$LOCK" "$SUSPEND" "$LOGOUT" "$REBOOT" "$SHUTDOWN" | \
    rofi -dmenu "${POWER_MENU_ARGS[@]}")

case "$chosen" in
    "$LOCK")     hyprlock ;;
    "$SUSPEND")  systemctl suspend ;;
    "$LOGOUT")   hyprctl dispatch exit ;;
    "$REBOOT")   systemctl reboot ;;
    "$SHUTDOWN") systemctl poweroff ;;
esac
