-- Dotfiles — ${THEME_NAME} (generated by switch-theme, do not edit)
--
-- Data only. lua/plugins/mini.lua reads this, applies it, and watches
-- this file, so a theme switch reaches a running nvim without a restart.
return {
  name = '${THEME_NAME}',
  appearance = '${THEME_APPEARANCE}',
  palette = {
    base00 = '#${BG}',
    base01 = '#${SURFACE}',
    base02 = '#${BG_ALT}',
    base03 = '#${MUTED}',
    base04 = '#${FG}',
    base05 = '#${FG}',
    base06 = '#${FG_BRIGHT}',
    base07 = '#${FG_BRIGHT}',
    base08 = '#${RED}',
    base09 = '#${ORANGE}',
    base0A = '#${YELLOW}',
    base0B = '#${GREEN}',
    base0C = '#${ACCENT}',
    base0D = '#${BLUE}',
    base0E = '#${PURPLE}',
    base0F = '#${ORANGE}',
  },
}
